# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: node:20-alpine
  script:
    - echo "Running Jest tests..."
    - cd front-end # Navigate to the front-end directory
    - npm install # Install dependencies
    - npm test # Run Jest tests
    - echo "Jest tests complete."

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

selenium-test-job:
  stage: test
  image: python:latest
  services:
    - selenium/standalone-chrome:latest
  script:
    - echo "Running Selenium tests..."
    - cd front-end/tests/selenium_tests
    - pip install -r requirements.txt # Install Python dependencies if necessary
    - python guitest.py # Replace this with the command to run your Selenium tests
    - echo "Selenium tests complete."

api-test-job:
  stage: test
  image: python:latest
  script:
    - echo "Running API tests..."
    - cd front-end/tests/api_tests
    - pip install -r requirements.txt # Install Python dependencies if necessary
    - python api_test.py # Replace this with the command to run your API tests
    - echo "API tests complete."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."


